/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  TouchableHighlight,
} from 'react-native';
import NiSdk from 'react-native-ni-sdk';

const orderResponse = {};

export default class App extends Component {
  onClickPay = () => {
    NiSdk.initiateCardPaymentUI(orderResponse, (status) => {
      console.log(status);
    });
  };

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>NISdk React Native</Text>
        <TouchableHighlight onPressOut={this.onClickPay}>
          <Text>Pay now</Text>
        </TouchableHighlight>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
